name: my-basic-workflow

on: 
  push:
    
run-name: Pipeline run by @${{ github.actor }}


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: echo ${{ github.sha }}
      - run: python main.py