name: my-basic-workflow

permissions:
  issues: write

on: 
  workflow_dispatch:
    inputs:
      msg:
        required: true 
        description: The message to be printed
      extra:
        required: false 
        description: Optional end text
    
env:
  blah: Workflow level env, defined before run-name


run-name: Pipeline run for commit ${{ github.sha }}


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{  vars.GREETING  }}
      - run: echo "${{  inputs.msg  }}" > output.txt
      - name: optioanl 
        if: ${{ inputs.extra }}
        run: echo "${{ inputs.extra }}" >> output.txt
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "title": "Failure: ${{ inputs.msg }}",
          "body": "Details: ${{ inputs.extra }}"
          }' \
          --fail
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./output.txt