name: my-basic-workflow

run-name: Pipeline run by @${{ github.actor }


on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: sleep 10
      - run: python main.py