name: my-basic-workflow

permissions:
  issues: write

on: 
  push: 
    branches: 
      - master
    
env:
  blah: Workflow level env, defined before run-name


run-name: Pipeline run for commit ${{ github.sha }}


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: echo ${{  vars.GREETING  }}
      - run: python main.py > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact.txt
          path: .