on:
  push

jobs:
  get-random:
    runs-on: ubuntu-latest
    steps:
      - id: some-random 
        uses: baker-james/action-random@v1
        with: 
          my-prefix: 'blah'
      - shell: bash 
        run: | 
          echo "random number is ${{ steps.some-random.outputs.my-random}}"

      